package com.duke.model.entity;

import java.util.ArrayList;
import java.util.List;

public class ManagerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public ManagerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andManidIsNull() {
            addCriterion("manid is null");
            return (Criteria) this;
        }

        public Criteria andManidIsNotNull() {
            addCriterion("manid is not null");
            return (Criteria) this;
        }

        public Criteria andManidEqualTo(Integer value) {
            addCriterion("manid =", value, "manid");
            return (Criteria) this;
        }

        public Criteria andManidNotEqualTo(Integer value) {
            addCriterion("manid <>", value, "manid");
            return (Criteria) this;
        }

        public Criteria andManidGreaterThan(Integer value) {
            addCriterion("manid >", value, "manid");
            return (Criteria) this;
        }

        public Criteria andManidGreaterThanOrEqualTo(Integer value) {
            addCriterion("manid >=", value, "manid");
            return (Criteria) this;
        }

        public Criteria andManidLessThan(Integer value) {
            addCriterion("manid <", value, "manid");
            return (Criteria) this;
        }

        public Criteria andManidLessThanOrEqualTo(Integer value) {
            addCriterion("manid <=", value, "manid");
            return (Criteria) this;
        }

        public Criteria andManidIn(List<Integer> values) {
            addCriterion("manid in", values, "manid");
            return (Criteria) this;
        }

        public Criteria andManidNotIn(List<Integer> values) {
            addCriterion("manid not in", values, "manid");
            return (Criteria) this;
        }

        public Criteria andManidBetween(Integer value1, Integer value2) {
            addCriterion("manid between", value1, value2, "manid");
            return (Criteria) this;
        }

        public Criteria andManidNotBetween(Integer value1, Integer value2) {
            addCriterion("manid not between", value1, value2, "manid");
            return (Criteria) this;
        }

        public Criteria andManpwdIsNull() {
            addCriterion("manpwd is null");
            return (Criteria) this;
        }

        public Criteria andManpwdIsNotNull() {
            addCriterion("manpwd is not null");
            return (Criteria) this;
        }

        public Criteria andManpwdEqualTo(String value) {
            addCriterion("manpwd =", value, "manpwd");
            return (Criteria) this;
        }

        public Criteria andManpwdNotEqualTo(String value) {
            addCriterion("manpwd <>", value, "manpwd");
            return (Criteria) this;
        }

        public Criteria andManpwdGreaterThan(String value) {
            addCriterion("manpwd >", value, "manpwd");
            return (Criteria) this;
        }

        public Criteria andManpwdGreaterThanOrEqualTo(String value) {
            addCriterion("manpwd >=", value, "manpwd");
            return (Criteria) this;
        }

        public Criteria andManpwdLessThan(String value) {
            addCriterion("manpwd <", value, "manpwd");
            return (Criteria) this;
        }

        public Criteria andManpwdLessThanOrEqualTo(String value) {
            addCriterion("manpwd <=", value, "manpwd");
            return (Criteria) this;
        }

        public Criteria andManpwdLike(String value) {
            addCriterion("manpwd like", value, "manpwd");
            return (Criteria) this;
        }

        public Criteria andManpwdNotLike(String value) {
            addCriterion("manpwd not like", value, "manpwd");
            return (Criteria) this;
        }

        public Criteria andManpwdIn(List<String> values) {
            addCriterion("manpwd in", values, "manpwd");
            return (Criteria) this;
        }

        public Criteria andManpwdNotIn(List<String> values) {
            addCriterion("manpwd not in", values, "manpwd");
            return (Criteria) this;
        }

        public Criteria andManpwdBetween(String value1, String value2) {
            addCriterion("manpwd between", value1, value2, "manpwd");
            return (Criteria) this;
        }

        public Criteria andManpwdNotBetween(String value1, String value2) {
            addCriterion("manpwd not between", value1, value2, "manpwd");
            return (Criteria) this;
        }

        public Criteria andMannameIsNull() {
            addCriterion("manname is null");
            return (Criteria) this;
        }

        public Criteria andMannameIsNotNull() {
            addCriterion("manname is not null");
            return (Criteria) this;
        }

        public Criteria andMannameEqualTo(String value) {
            addCriterion("manname =", value, "manname");
            return (Criteria) this;
        }

        public Criteria andMannameNotEqualTo(String value) {
            addCriterion("manname <>", value, "manname");
            return (Criteria) this;
        }

        public Criteria andMannameGreaterThan(String value) {
            addCriterion("manname >", value, "manname");
            return (Criteria) this;
        }

        public Criteria andMannameGreaterThanOrEqualTo(String value) {
            addCriterion("manname >=", value, "manname");
            return (Criteria) this;
        }

        public Criteria andMannameLessThan(String value) {
            addCriterion("manname <", value, "manname");
            return (Criteria) this;
        }

        public Criteria andMannameLessThanOrEqualTo(String value) {
            addCriterion("manname <=", value, "manname");
            return (Criteria) this;
        }

        public Criteria andMannameLike(String value) {
            addCriterion("manname like", value, "manname");
            return (Criteria) this;
        }

        public Criteria andMannameNotLike(String value) {
            addCriterion("manname not like", value, "manname");
            return (Criteria) this;
        }

        public Criteria andMannameIn(List<String> values) {
            addCriterion("manname in", values, "manname");
            return (Criteria) this;
        }

        public Criteria andMannameNotIn(List<String> values) {
            addCriterion("manname not in", values, "manname");
            return (Criteria) this;
        }

        public Criteria andMannameBetween(String value1, String value2) {
            addCriterion("manname between", value1, value2, "manname");
            return (Criteria) this;
        }

        public Criteria andMannameNotBetween(String value1, String value2) {
            addCriterion("manname not between", value1, value2, "manname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table manager
     *
     * @mbg.generated do_not_delete_during_merge Sun Oct 11 17:18:24 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table manager
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}