package com.duke.model.entity;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manid
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    private Integer manid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manpwd
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    private String manpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manname
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    private String manname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manid
     *
     * @return the value of manager.manid
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public Integer getManid() {
        return manid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manid
     *
     * @param manid the value for manager.manid
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void setManid(Integer manid) {
        this.manid = manid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manpwd
     *
     * @return the value of manager.manpwd
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public String getManpwd() {
        return manpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manpwd
     *
     * @param manpwd the value for manager.manpwd
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void setManpwd(String manpwd) {
        this.manpwd = manpwd == null ? null : manpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manname
     *
     * @return the value of manager.manname
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public String getManname() {
        return manname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manname
     *
     * @param manname the value for manager.manname
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void setManname(String manname) {
        this.manname = manname == null ? null : manname.trim();
    }

	@Override
	public String toString() {
		return "Manager [manid=" + manid + ", manpwd=" + manpwd + ", manname="
				+ manname + "]";
	}

	public Manager(Integer manid, String manpwd, String manname) {
		super();
		this.manid = manid;
		this.manpwd = manpwd;
		this.manname = manname;
	}

	public Manager() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}