package com.duke.model.entity;

import java.util.Date;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userid
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userpwd
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    private String userpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.useremail
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    private String useremail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.create_time
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.loginsign
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    private Integer loginsign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.operator_time
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userid
     *
     * @return the value of userinfo.userid
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userid
     *
     * @param userid the value for userinfo.userid
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userpwd
     *
     * @return the value of userinfo.userpwd
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userpwd
     *
     * @param userpwd the value for userinfo.userpwd
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.useremail
     *
     * @return the value of userinfo.useremail
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.useremail
     *
     * @param useremail the value for userinfo.useremail
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.create_time
     *
     * @return the value of userinfo.create_time
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.create_time
     *
     * @param createTime the value for userinfo.create_time
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.loginsign
     *
     * @return the value of userinfo.loginsign
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public Integer getLoginsign() {
        return loginsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.loginsign
     *
     * @param loginsign the value for userinfo.loginsign
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void setLoginsign(Integer loginsign) {
        this.loginsign = loginsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.operator_time
     *
     * @return the value of userinfo.operator_time
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.operator_time
     *
     * @param operatorTime the value for userinfo.operator_time
     *
     * @mbg.generated Sun Oct 11 17:18:24 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

	@Override
	public String toString() {
		return "Userinfo [userid=" + userid + ", username=" + username
				+ ", userpwd=" + userpwd + ", useremail=" + useremail
				+ ", createTime=" + createTime + ", loginsign=" + loginsign
				+ ", operatorTime=" + operatorTime + "]";
	}

	public Userinfo(Integer userid, String username, String userpwd,
			String useremail, Date createTime, Integer loginsign,
			Date operatorTime) {
		super();
		this.userid = userid;
		this.username = username;
		this.userpwd = userpwd;
		this.useremail = useremail;
		this.createTime = createTime;
		this.loginsign = loginsign;
		this.operatorTime = operatorTime;
	}

	public Userinfo() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}